### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by liaojiacai** [marsmarcin/Visual-of-Social-GAN#2]
when run the commend:python plot_model01.py --model_path models\sgan-models\01.It occours:

Traceback (most recent call last):
  File "plot_model01.py", line 113, in <module>
    main(args)
  File "plot_model01.py", line 107, in main
    evaluate(_args, loader, generator, args.num_samples)
  File "plot_model01.py", line 80, in evaluate
    aa=np.concatenate((input_a,gt),axis=0)
  File "E:\Anaconda\envs\pytorch-gpu\lib\site-packages\torch\tensor.py", line 450, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

How to solve this problem? Thank you in advance!

**Comment by marsmarcin** [comment]
”Use Tensor.cpu() to copy the tensor to host memory first.“ it can  help

**Comment by liaojiacai** [comment]
> 
> 
> ”Use Tensor.cpu() to copy the tensor to host memory first.“ it can help

@marsmarcin 
Change this line?"batch = [tensor.cuda() for tensor in batch]"
I replace the "tensor.cuda()" with "tensor.cpu()", after that,there is a new error:
-----------------------------
 File "plot_model01.py", line 113, in <module>
    main(args)
  File "plot_model01.py", line 107, in main
    evaluate(_args, loader, generator, args.num_samples)
  File "plot_model01.py", line 72, in evaluate
    obs_traj, obs_traj_rel, seq_start_end
  File "E:\Anaconda\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\DL_file_code_video\DL_VIDEO\5\Deep Learning for Self-Driving Cars\P\p47social-gan\sgan-master\sgan-master\sgan\models.py", line 508, in forward
    final_encoder_h = self.encoder(obs_traj_rel)
  File "E:\Anaconda\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\DL_file_code_video\DL_VIDEO\5\Deep Learning for Self-Driving Cars\P\p47social-gan\sgan-master\sgan-master\sgan\models.py", line 63, in forward
    obs_traj_embedding = self.spatial_embedding(obs_traj.view(-1, 2))
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\aten\src\th\generic/THTensor.cpp:213
---------------------------------

So,how to modify the code?

**Comment by marsmarcin** [comment]
every line use "xx.cuda()",you may change them  into "xx.cpu()"

**Comment by liaojiacai** [comment]
@marsmarcin 
My cuda device is not problem. The test result show as fellow:
>>> import torch
>>> print(torch.cuda.is_available())
True

So, if i want use the cuda as the same as you source code, How can i to avoid the Tensor problem?I gusses you have been run it on GPU with no priblem. Thank you.

**Comment by marsmarcin** [comment]
you may install the wrong version with your GPU and nvidia you can google it in detail

**Comment by liaojiacai** [comment]
@marsmarcin 
But, There is no problem when I run the training and evaluate code,those are runing on the GPU. Maybe I will spend some time to have a good look about you code.

**Comment by liaojiacai** [comment]
@marsmarcin Hi, I solve the problem.
The question is there:
"
                aa=np.concatenate((input_a,gt),axis=0)
                bb=np.concatenate((input_a,out_a),axis=0)
"
the CUDA tensor con't be used direct in the Numpy.Please replace this two lines with:
"
                aa=np.concatenate((input_a.cuda().data.cpu().numpy(),gt.cuda().data.cpu().numpy()),axis=0)
                bb=np.concatenate((input_a.cuda().data.cpu().numpy(),out_a.cuda().data.cpu().numpy()),axis=0)
"
Maybe there is a different about Tensor to numpy and CUDA Tensor to numpy.

**Comment by davidglavas** [comment]
To solve CUDA gpu/cpu issues you have to modify three lines:

replace checkpoint = `checkpoint = torch.load(path)` by `checkpoint = torch.load(path, map_location='cpu')`

replace batch = `generator.cuda()` by `generator.cpu()`

replace batch = `[tensor.cuda() for tensor in batch]` by `batch = [tensor.cpu() for tensor in batch]`

**Comment by bowenroom** [comment]
> @marsmarcin Hi, I solve the problem.
> The question is there:
> "
> aa=np.concatenate((input_a,gt),axis=0)
> bb=np.concatenate((input_a,out_a),axis=0)
> "
> the CUDA tensor con't be used direct in the Numpy.Please replace this two lines with:
> "
> aa=np.concatenate((input_a.cuda().data.cpu().numpy(),gt.cuda().data.cpu().numpy()),axis=0)
> bb=np.concatenate((input_a.cuda().data.cpu().numpy(),out_a.cuda().data.cpu().numpy()),axis=0)
> "
> Maybe there is a different about Tensor to numpy and CUDA Tensor to numpy.

Can you get the right plot after fixing the code? I could only get the ground line but cannot get the predicted line after using your code
![image](https://user-images.githubusercontent.com/13314638/69319646-8b401e80-0c7a-11ea-8eb5-1a5dd4abd985.png)

**Comment by PPaulthi** [comment]
After following all the steps above I get the following error:

`RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`
