### ISSUE TITLE
no figure appears when I run the code on server

### ISSUE THREAD

**Issue by mingbocui** [marsmarcin/Visual-of-Social-GAN#3]
Hi,

Thanks for your code. I am running the code on the server, the code runs correctly but there is no figure appears. Are there some additional packages for producing figures need to be installed to run your code? Hope for your reply. Many thanks.

Warm regards

**Comment by marsmarcin** [comment]
no need to run this on a server. just because it has no monitor...you can change the code to save in a path or just run on your PC..
(你是拿你的电脑远程登陆的服务器运行的吧，你这样肯定看不到图像啊，要么你直接在服务器上跑，要么在你自己的电脑上跑)

**Comment by mingbocui** [comment]
感谢回复！一直拿电脑远程登服务器，我之前在服务器上开jupyter也没研究出来怎么让它在notebook里出图（加了%matplotlib inline）,看来只能本地上跑了:(

**Comment by renegaderl** [comment]
> no need to run this on a server. just because it has no monitor...you can change the code to save in a path or just run on your PC..
> (你是拿你的电脑远程登陆的服务器运行的吧，你这样肯定看不到图像啊，要么你直接在服务器上跑，要么在你自己的电脑上跑)

哈喽，我也是远程服务器跑的代码，不过我改了一下把生成的图片给保存下来。三个脚本里面第一个生成的图片没有问题，但是另外两个都只有坐标轴没有生成的轨迹

**Comment by marsmarcin** [comment]
你们可以用xshell，点击文件---属性---隧道,设置实现服务器上的图片可视化

**Comment by marsmarcin** [comment]
> > no need to run this on a server. just because it has no monitor...you can change the code to save in a path or just run on your PC..
> > (你是拿你的电脑远程登陆的服务器运行的吧，你这样肯定看不到图像啊，要么你直接在服务器上跑，要么在你自己的电脑上跑)
> 
> 哈喽，我也是远程服务器跑的代码，不过我改了一下把生成的图片给保存下来。三个脚本里面第一个生成的图片没有问题，但是另外两个都只有坐标轴没有生成的轨迹

看一下我下面的那条

**Comment by renegaderl** [comment]
多谢！我试一下

**Comment by marsmarcin** [comment]
> 多谢！我试一下

搞不明白就百度搜吧,有教程的
