### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TrajectoryGenerator

### ISSUE THREAD

**Issue by Psychic-DL** [marsmarcin/Visual-of-Social-GAN#5]
Hi，the following error occurred when I ran this program.

RuntimeError: Error(s) in loading state_dict for TrajectoryGenerator:
	size mismatch for mlp_decoder_context.2.weight: copying a param with shape torch.Size([24, 64]) from checkpoint, the shape in current model is torch.Size([32, 64]).
	size mismatch for mlp_decoder_context.2.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([32]).

Would you please help me and tell me how to solve this problem?Thx!

**Comment by marsmarcin** [comment]
> Hi，the following error occurred when I ran this program.
> 
> RuntimeError: Error(s) in loading state_dict for TrajectoryGenerator:
> size mismatch for mlp_decoder_context.2.weight: copying a param with shape torch.Size([24, 64]) from checkpoint, the shape in current model is torch.Size([32, 64]).
> size mismatch for mlp_decoder_context.2.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([32]).
> 
> Would you please help me and tell me how to solve this problem?Thx!
You may load wrong weight for this project

**Comment by Psychic-DL** [comment]
> Hi，the following error occurred when I ran this program.
> RuntimeError: Error(s) in loading state_dict for TrajectoryGenerator:
> size mismatch for mlp_decoder_context.2.weight: copying a param with shape torch.Size([24, 64]) from checkpoint, the shape in current model is torch.Size([32, 64]).
> size mismatch for mlp_decoder_context.2.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([32]).
> Would you please help me and tell me how to solve this problem?Thx!
> You may load wrong weight for this project

Thank you for your reply, I have found the cause of the error.
